# -*- coding: utf-8 -*-
"""silver_prod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwLt6YQKjhmptZBczTZ2lwJ-IY6wGjgh
"""

# Welcome to your new notebook
# Type here in the cell editor to add code!

df = spark.read.format("csv").option("header","true").load("Files/Bronzebronze_production_data/production_data.csv")
# df now is a Spark DataFrame containing CSV data from "Files/Bronzebronze_production_data/production_data.csv".
display(df)

from pyspark.sql.functions import col, trim, upper
from pyspark.sql.types import IntegerType, DoubleType

silver_df = (df
.withColumn("ProdID", trim(upper(col("ProdID"))))
.withColumn("PlantID", trim(upper(col("PlantID"))))
    .withColumn("PlannedQty", col("PlannedQty").cast(IntegerType()))
    .withColumn("ActualQty", col("ActualQty").cast(IntegerType()))
    .withColumn("RejectedQty", col("RejectedQty").cast(IntegerType()))
)

display(silver_df)

silver_df = silver_df.withColumn(
    "GoodQty",
    col("ActualQty") - col("RejectedQty")
)

from pyspark.sql.functions import when

silver_df = silver_df.withColumn("RejectedFlag",
when(col("RejectedQty") > col("ActualQty"), 1).otherwise(0))

display(silver_df)

silver_df = silver_df.withColumn(
    "MaterialusedinKGs",
    col("ActualQty") * 0.8
)

silver_df = silver_df.withColumn(
    "ProductionVarianceQty",
    col("PlannedQty") - col("ActualQty")
)

silver_df = silver_df.withColumn(
    "StandardMaterialCost",
    col("MaterialusedinKGs") * 180
)

silver_df = silver_df.withColumn(
    "OverProductionFlag",
    when(col("ActualQty") > col("PlannedQty") * 1.2,1).otherwise(0)
)

display(silver_df)

silver_path = "abfss://Fabric_Test@onelake.dfs.fabric.microsoft.com/Test_Lakehouse.Lakehouse/Files/Silver Layer Files"
silver_df.write.mode("overwrite") \
    .parquet(f"{silver_path}/silver_production")

df_check = spark.read.parquet(f"{silver_path}/silver_production")
display(df_check)

